---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: golang-gin-demo
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./deploy/kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: golang-gin-demo

