apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: golang-gin-demo
  namespace: wego-system
resources:
- app.yaml
- golang-gin-demo-gitops-deploy.yaml
- golang-gin-demo-gitops-source.yaml
